language: java
env:
  matrix:
    - PLATFORM=acf10-linux64
    - PLATFORM=railo42beta
    - PLATFORM=railo41

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c3bc8e90100d9446a065
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

install: ant -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM install-ci-deps
script: ant -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM test-ci
